# Multiindex Generation

## Multiple indices per row (row labels)

### 1. Using set_index()

In [2]:
import pandas as pd
import seaborn as sns

In [3]:
diamonds = sns.load_dataset('diamonds')

In [4]:
diamonds.shape

(53940, 10)

In [5]:
sorted_df = diamonds.sort_values(['cut','clarity'])
multiind_df = sorted_df.set_index(['cut', 'clarity'])
multiind_df

               carat color  depth  table  price     x     y     z
cut   clarity
Ideal IF        0.52     F   62.2   55.0   2783  5.14  5.18  3.21
      IF        0.55     G   60.9   57.0   2789  5.28  5.30  3.22
      IF        0.64     G   61.3   56.0   2790  5.54  5.58  3.41
      IF        0.61     G   62.3   56.0   2800  5.43  5.45  3.39
      IF        0.53     F   61.9   54.0   2802  5.22  5.25  3.24
...              ...   ...    ...    ...    ...   ...   ...   ...
Fair  I1        1.30     E   66.5   58.0   2571  6.79  6.75  4.50
      I1        1.29     H   67.7   62.0   2596  6.69  6.59  4.50
      I1        1.20     F   65.7   56.0   2622  6.65  6.58  4.35
      I1        1.20     G   64.4   55.0   2655  6.77  6.61  4.31
      I1        1.00     G   61.7   57.0   2723  6.39  6.28  3.91

[53940 rows x 8 columns]

In [5]:
#Using an unsorted df
diamonds.set_index(['cut','clarity'])

                   carat color  depth  table  price     x     y     z
cut       clarity
Ideal     SI2       0.23     E   61.5   55.0    326  3.95  3.98  2.43
Premium   SI1       0.21     E   59.8   61.0    326  3.89  3.84  2.31
Good      VS1       0.23     E   56.9   65.0    327  4.05  4.07  2.31
Premium   VS2       0.29     I   62.4   58.0    334  4.20  4.23  2.63
Good      SI2       0.31     J   63.3   58.0    335  4.34  4.35  2.75
...                  ...   ...    ...    ...    ...   ...   ...   ...
Ideal     SI1       0.72     D   60.8   57.0   2757  5.75  5.76  3.50
Good      SI1       0.72     D   63.1   55.0   2757  5.69  5.75  3.61
Very Good SI1       0.70     D   62.8   60.0   2757  5.66  5.68  3.56
Premium   SI2       0.86     H   61.0   58.0   2757  6.15  6.12  3.74
Ideal     SI2       0.75     D   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 8 columns]

In [6]:
diamonds.shape

(53940, 10)

In [7]:
multiind_df.shape

(53940, 8)

In [8]:
multiind_df.index

MultiIndex([('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ('Ideal', 'IF'),
            ...
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1'),
            ( 'Fair', 'I1')],
           names=['cut', 'clarity'], length=53940)

In [9]:
#set_index drops original index by default
multiind_df = sorted_df.set_index(['cut', 'clarity'])
multiind_df.set_index('carat')

      color  depth  table  price     x     y     z
carat
0.52      F   62.2   55.0   2783  5.14  5.18  3.21
0.55      G   60.9   57.0   2789  5.28  5.30  3.22
0.64      G   61.3   56.0   2790  5.54  5.58  3.41
0.61      G   62.3   56.0   2800  5.43  5.45  3.39
0.53      F   61.9   54.0   2802  5.22  5.25  3.24
...     ...    ...    ...    ...   ...   ...   ...
1.30      E   66.5   58.0   2571  6.79  6.75  4.50
1.29      H   67.7   62.0   2596  6.69  6.59  4.50
1.20      F   65.7   56.0   2622  6.65  6.58  4.35
1.20      G   64.4   55.0   2655  6.77  6.61  4.31
1.00      G   61.7   57.0   2723  6.39  6.28  3.91

[53940 rows x 7 columns]

In [9]:
#First reset index then set the index to retain previous indices as columns
multiind_df.reset_index().set_index('carat')

         cut clarity color  depth  table  price     x     y     z
carat
0.52   Ideal      IF     F   62.2   55.0   2783  5.14  5.18  3.21
0.55   Ideal      IF     G   60.9   57.0   2789  5.28  5.30  3.22
0.64   Ideal      IF     G   61.3   56.0   2790  5.54  5.58  3.41
0.61   Ideal      IF     G   62.3   56.0   2800  5.43  5.45  3.39
0.53   Ideal      IF     F   61.9   54.0   2802  5.22  5.25  3.24
...      ...     ...   ...    ...    ...    ...   ...   ...   ...
1.30    Fair      I1     E   66.5   58.0   2571  6.79  6.75  4.50
1.29    Fair      I1     H   67.7   62.0   2596  6.69  6.59  4.50
1.20    Fair      I1     F   65.7   56.0   2622  6.65  6.58  4.35
1.20    Fair      I1     G   64.4   55.0   2655  6.77  6.61  4.31
1.00    Fair      I1     G   61.7   57.0   2723  6.39  6.28  3.91

[53940 rows x 9 columns]

#### Add multiindex columns in read_csv()

In [10]:
pd.read_csv('diamonds.csv', index_col=[1,3]).sort_index()

                   carat color  depth  table  price     x     y     z
cut       clarity
Fair      I1        1.01     E   64.5   58.0   2788  6.29  6.21  4.03
          I1        1.00     G   66.4   59.0   2808  6.16  6.09  4.07
          I1        1.20     F   64.6   56.0   2809  6.73  6.66  4.33
          I1        1.19     H   65.1   59.0   2892  6.62  6.55  4.29
          I1        1.17     I   65.4   62.0   2935  6.68  6.57  4.33
...                  ...   ...    ...    ...    ...   ...   ...   ...
Very Good VVS2      0.70     G   63.6   57.0   2681  5.59  5.63  3.57
          VVS2      0.71     H   63.0   56.0   2695  5.63  5.68  3.56
          VVS2      0.71     H   63.0   58.0   2709  5.64  5.72  3.58
          VVS2      0.58     D   60.0   55.0   2714  5.44  5.49  3.28
          VVS2      0.75     I   62.0   59.0   2749  5.81  5.83  3.61

[53940 rows x 8 columns]

### 2. groupby() many columns

In [10]:
#groupby cut and clarity and aggregate the values by sum. Other aggregation functions are median,...
grouped_df = diamonds.groupby(['cut','color']).max()
grouped_df

                 carat  depth  table  price      x      y      z
cut       color
Ideal     D       2.75   64.5   62.0  18693   9.04   8.98   5.49
          E       2.28   65.5   62.0  18729   8.52  31.80   5.25
          F       2.45   65.3   63.0  18780   8.67   8.64   5.36
          G       2.54   64.1   62.0  18806   8.75   8.69   5.46
          H       3.50   65.1   62.0  18760   9.65   9.59   6.03
          I       3.22   66.7   62.0  18779   9.49   9.42   5.92
          J       3.01   65.4   62.0  18508   9.25   9.20   5.86
Premium   D       2.57   63.0   62.0  18575   8.99   8.94   5.28
          E       3.05   63.0   62.0  18477   9.26   9.25   5.66
          F       3.01   63.0   62.0  18791   9.24   9.13   5.73
          G       3.01   63.0   62.0  18741   9.44   9.37   5.62
          H       3.24   63.0   62.0  18795   9.44  58.90   8.06
          I       4.01   63.0   62.0  18823  10.14  10.10   6.17
          J       4.01   63.0   62.0  18710  10.02   9.94   6.24
Very Good D       2.58   64.7   64.0  18542   9.08   9.01   5.33
          E       2.51   64.5   65.0  18731   8.65   8.60  31.80
          F       2.48   64.5   65.0  18777   8.64   8.55   5.45
          G       2.52   64.9   66.0  18818   8.65   8.61   5.45
          H       3.00   64.7   65.0  18803   9.23   9.10   5.77
          I       4.00   64.4   65.0  18500  10.01   9.94   6.31
          J       2.74   64.1   63.0  18430   8.89   8.93   5.47
Good      D       2.04   67.0   66.0  18468   8.15   8.11   5.11
          E       3.00   65.9   65.0  18236   9.08   8.96   5.79
          F       2.67   66.5   66.0  18686   8.69   8.64   5.54
          G       2.80   65.8   66.0  18788   8.90   8.85   5.44
          H       3.01   66.1   65.0  18640   9.44   9.38   5.58
          I       3.01   65.9   66.0  18707   9.38   9.31   5.77
          J       3.00   66.0   65.0  18325   9.32   9.19   5.50
Fair      D       3.40   71.6   73.0  16386   9.42   9.34   6.27
          E       2.04   79.0   73.0  15584   8.16   8.04   5.24
          F       2.58   71.0   95.0  17995   8.58   8.51   5.57
          G       2.60   72.9   76.0  18574   8.75   8.69   6.16
          H       4.13   71.8   73.0  18565  10.00   9.85   6.43
          I       3.02   71.3   70.0  18242   9.11   9.02   5.91
          J       5.01   73.6   68.0  18531  10.74  10.54   6.98

In [11]:
diamonds.shape

(53940, 10)

In [12]:
grouped_df.shape

(35, 7)

## Multiple column headers

### 1. Groupby() by many columns then unstack()

In [13]:
#groupby cut and clarity and aggregate the values by median this time. Other aggregation functions are sum,...
grouped_df = diamonds.groupby(['cut','color']).max()
grouped_df

                 carat  depth  table  price      x      y      z
cut       color
Ideal     D       2.75   64.5   62.0  18693   9.04   8.98   5.49
          E       2.28   65.5   62.0  18729   8.52  31.80   5.25
          F       2.45   65.3   63.0  18780   8.67   8.64   5.36
          G       2.54   64.1   62.0  18806   8.75   8.69   5.46
          H       3.50   65.1   62.0  18760   9.65   9.59   6.03
          I       3.22   66.7   62.0  18779   9.49   9.42   5.92
          J       3.01   65.4   62.0  18508   9.25   9.20   5.86
Premium   D       2.57   63.0   62.0  18575   8.99   8.94   5.28
          E       3.05   63.0   62.0  18477   9.26   9.25   5.66
          F       3.01   63.0   62.0  18791   9.24   9.13   5.73
          G       3.01   63.0   62.0  18741   9.44   9.37   5.62
          H       3.24   63.0   62.0  18795   9.44  58.90   8.06
          I       4.01   63.0   62.0  18823  10.14  10.10   6.17
          J       4.01   63.0   62.0  18710  10.02   9.94   6.24
Very Good D       2.58   64.7   64.0  18542   9.08   9.01   5.33
          E       2.51   64.5   65.0  18731   8.65   8.60  31.80
          F       2.48   64.5   65.0  18777   8.64   8.55   5.45
          G       2.52   64.9   66.0  18818   8.65   8.61   5.45
          H       3.00   64.7   65.0  18803   9.23   9.10   5.77
          I       4.00   64.4   65.0  18500  10.01   9.94   6.31
          J       2.74   64.1   63.0  18430   8.89   8.93   5.47
Good      D       2.04   67.0   66.0  18468   8.15   8.11   5.11
          E       3.00   65.9   65.0  18236   9.08   8.96   5.79
          F       2.67   66.5   66.0  18686   8.69   8.64   5.54
          G       2.80   65.8   66.0  18788   8.90   8.85   5.44
          H       3.01   66.1   65.0  18640   9.44   9.38   5.58
          I       3.01   65.9   66.0  18707   9.38   9.31   5.77
          J       3.00   66.0   65.0  18325   9.32   9.19   5.50
Fair      D       3.40   71.6   73.0  16386   9.42   9.34   6.27
          E       2.04   79.0   73.0  15584   8.16   8.04   5.24
          F       2.58   71.0   95.0  17995   8.58   8.51   5.57
          G       2.60   72.9   76.0  18574   8.75   8.69   6.16
          H       4.13   71.8   73.0  18565  10.00   9.85   6.43
          I       3.02   71.3   70.0  18242   9.11   9.02   5.91
          J       5.01   73.6   68.0  18531  10.74  10.54   6.98

In [14]:
#unstack cut for all numeric features
grouped_df = diamonds.groupby(['cut','color']).max()
unstacked_df = grouped_df.unstack('cut')
unstacked_df

      carat                               depth                                \
cut   Ideal Premium Very Good  Good  Fair Ideal Premium Very Good  Good  Fair
color
D      2.75    2.57      2.58  2.04  3.40  64.5    63.0      64.7  67.0  71.6
E      2.28    3.05      2.51  3.00  2.04  65.5    63.0      64.5  65.9  79.0
F      2.45    3.01      2.48  2.67  2.58  65.3    63.0      64.5  66.5  71.0
G      2.54    3.01      2.52  2.80  2.60  64.1    63.0      64.9  65.8  72.9
H      3.50    3.24      3.00  3.01  4.13  65.1    63.0      64.7  66.1  71.8
I      3.22    4.01      4.00  3.01  3.02  66.7    63.0      64.4  65.9  71.3
J      3.01    4.01      2.74  3.00  5.01  65.4    63.0      64.1  66.0  73.6

       ...      y                                    z                    \
cut    ...  Ideal Premium Very Good  Good   Fair Ideal Premium Very Good
color  ...
D      ...   8.98    8.94      9.01  8.11   9.34  5.49    5.28      5.33
E      ...  31.80    9.25      8.60  8.96   8.04  5.25    5.66     31.80
F      ...   8.64    9.13      8.55  8.64   8.51  5.36    5.73      5.45
G      ...   8.69    9.37      8.61  8.85   8.69  5.46    5.62      5.45
H      ...   9.59   58.90      9.10  9.38   9.85  6.03    8.06      5.77
I      ...   9.42   10.10      9.94  9.31   9.02  5.92    6.17      6.31
J      ...   9.20    9.94      8.93  9.19  10.54  5.86    6.24      5.47


cut    Good  Fair
color
D      5.11  6.27
E      5.79  5.24
F      5.54  5.57
G      5.44  6.16
H      5.58  6.43
I      5.77  5.91
J      5.50  6.98

[7 rows x 35 columns]

In [15]:
#The default for unstack unstacks the innermost index
grouped_df.unstack()

          carat                                     depth              ...  \
color         D     E     F     G     H     I     J     D     E     F  ...
cut                                                                    ...
Ideal      2.75  2.28  2.45  2.54  3.50  3.22  3.01  64.5  65.5  65.3  ...
Premium    2.57  3.05  3.01  3.01  3.24  4.01  4.01  63.0  63.0  63.0  ...
Very Good  2.58  2.51  2.48  2.52  3.00  4.00  2.74  64.7  64.5  64.5  ...
Good       2.04  3.00  2.67  2.80  3.01  3.01  3.00  67.0  65.9  66.5  ...
Fair       3.40  2.04  2.58  2.60  4.13  3.02  5.01  71.6  79.0  71.0  ...

               y                   z
color          H      I      J     D      E     F     G     H     I     J
cut
Ideal       9.59   9.42   9.20  5.49   5.25  5.36  5.46  6.03  5.92  5.86
Premium    58.90  10.10   9.94  5.28   5.66  5.73  5.62  8.06  6.17  6.24
Very Good   9.10   9.94   8.93  5.33  31.80  5.45  5.45  5.77  6.31  5.47
Good        9.38   9.31   9.19  5.11   5.79  5.54  5.44  5.58  5.77  5.50
Fair        9.85   9.02  10.54  6.27   5.24  5.57  6.16  6.43  5.91  6.98

[5 rows x 49 columns]

### 2. Groupby() and aggregate by many functions

In [16]:
#Aggregate using more than one function
diamonds.groupby('cut').agg(['median','max','mean'])

           carat                  depth                   table        \
          median   max      mean median   max       mean median   max
cut
Ideal       0.54  3.50  0.702837   61.8  66.7  61.709401   56.0  63.0
Premium     0.86  4.01  0.891955   61.4  63.0  61.264673   59.0  62.0
Very Good   0.71  4.00  0.806381   62.1  64.9  61.818275   58.0  66.0
Good        0.82  3.01  0.849185   63.4  67.0  62.365879   58.0  66.0
Fair        1.00  5.01  1.046137   65.0  79.0  64.041677   58.0  95.0

                       price  ...                   x                       y  \
                mean  median  ...         mean median    max      mean median
cut                           ...
Ideal      55.951668  1810.0  ...  3457.541970  5.250   9.65  5.507451   5.26
Premium    58.746095  3185.0  ...  4584.257704  6.110  10.14  5.973887   6.06
Very Good  57.956150  2648.0  ...  3981.759891  5.740  10.01  5.740696   5.77
Good       58.694639  3050.5  ...  3928.864452  5.980   9.44  5.838785   5.99
Fair       59.053789  3282.0  ...  4358.757764  6.175  10.74  6.246894   6.10

                                z
             max      mean median    max      mean
cut
Ideal      31.80  5.520080   3.23   6.03  3.401448
Premium    58.90  5.944879   3.72   8.06  3.647124
Very Good   9.94  5.770026   3.56  31.80  3.559801
Good        9.38  5.850744   3.70   5.79  3.639507
Fair       10.54  6.182652   3.97   6.98  3.982770

[5 rows x 21 columns]

In [17]:
#grouping by one column and one aggregation funtion only yield one index and one column header. 
#Note that the column headers look like 2 levels but it's actually one just because the index now has a name 'cut'.
#The usual range index appears with no name
diamonds.groupby('cut').agg('median')

           carat  depth  table   price      x     y     z
cut
Ideal       0.54   61.8   56.0  1810.0  5.250  5.26  3.23
Premium     0.86   61.4   59.0  3185.0  6.110  6.06  3.72
Very Good   0.71   62.1   58.0  2648.0  5.740  5.77  3.56
Good        0.82   63.4   58.0  3050.5  5.980  5.99  3.70
Fair        1.00   65.0   58.0  3282.0  6.175  6.10  3.97

### 3. Using pivot_table to convert rows into columns

In [18]:
diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [19]:
diamonds.pivot_table(
    values = 'price',
    index = 'color',
    columns = ['clarity','cut'],
    aggfunc='median')

clarity      IF                                        VVS1                    \
cut       Ideal  Premium Very Good     Good    Fair   Ideal Premium Very Good
color
D        4184.5  10129.0    9182.0  15081.0  1440.0  1547.0  1582.0    1158.0
E        1207.0   1207.0    1421.0    912.0     NaN  1057.0  1044.0     674.5
F         979.0   1085.0    1284.0   1806.0  2502.5  1124.0  1356.0     932.5
G        1014.0   1148.0    1271.0   1706.5  1488.0  1114.0  1155.0    1013.0
H        1055.0   1097.0    1187.0   4553.5     NaN  1029.5   907.0     967.0
I         865.0   1056.0    2057.0    915.5     NaN   974.0  1033.0    1164.0
J         828.0   5844.0     828.0   1557.0     NaN   994.0  7284.5    2093.0

clarity                  ...     SI2                                    \
cut        Good    Fair  ...   Ideal Premium Very Good    Good    Fair
color                    ...
D        1159.0  1792.0  ...  2533.5  4007.0    3965.0  3540.0  3473.0
E         826.0  2805.0  ...  3429.0  3846.0    3674.0  3185.5  3437.5
F         965.0  1040.0  ...  3246.0  4043.0    3770.0  3886.0  3540.0
G        1235.0  2797.0  ...  3903.5  4273.5    3891.0  3852.0  3598.5
H         893.0  4115.0  ...  4536.0  4872.0    4483.0  3965.0  4129.0
I        1737.0  4194.0  ...  5237.5  5216.5    4957.5  4953.0  4704.0
J        4633.0  1691.0  ...  4684.5  5310.0    4341.0  4559.0  3302.0

clarity      I1
cut       Ideal Premium Very Good    Good    Fair
color
D        3886.0  3740.0    2618.0  4013.5  5538.5
E        3552.0  3343.5    3256.0  3484.0  2036.0
F        3544.0  2999.5    3774.0  2098.0  1570.0
G        3909.5  3045.0    3014.0  3127.0  1954.0
H        3951.0  3202.0    4256.0  3156.5  3339.5
I        3328.0  3636.5    3789.5  3098.0  2396.0
J        9454.0  2825.0    3770.0  3356.0  5405.0

[7 rows x 40 columns]

### 4. Using the pd.crosstab() function

In [20]:
diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [21]:
pd.crosstab(
    index = diamonds['color'],
    columns = [diamonds['clarity'],
               diamonds['cut']],
    normalize = 'columns')

clarity        IF                                              VVS1            \
cut         Ideal   Premium Very Good      Good      Fair     Ideal   Premium
color
D        0.023102  0.043478  0.085821  0.126761  0.333333  0.070347  0.064935
E        0.065182  0.117391  0.160448  0.126761  0.000000  0.163654  0.170455
F        0.221122  0.134783  0.250000  0.211268  0.444444  0.214949  0.129870
G        0.405116  0.378261  0.294776  0.309859  0.222222  0.290181  0.277597
H        0.186469  0.173913  0.108209  0.056338  0.000000  0.159257  0.181818
I        0.078383  0.100000  0.070896  0.084507  0.000000  0.087445  0.136364
J        0.020627  0.052174  0.029851  0.084507  0.000000  0.014167  0.038961

clarity                                ...       SI2                      \
cut     Very Good      Good      Fair  ...     Ideal   Premium Very Good
color                                  ...
D        0.065906  0.069892  0.176471  ...  0.137028  0.142760  0.149524
E        0.215463  0.231183  0.176471  ...  0.180523  0.175992  0.211905
F        0.220532  0.188172  0.294118  ...  0.174365  0.177348  0.163333
G        0.240811  0.220430  0.176471  ...  0.187067  0.166836  0.155714
H        0.145754  0.166667  0.058824  ...  0.173210  0.176670  0.163333
I        0.087452  0.118280  0.058824  ...  0.105466  0.105799  0.095238
J        0.024081  0.005376  0.058824  ...  0.042340  0.054595  0.060952

clarity                            I1
cut          Good      Fair     Ideal   Premium Very Good      Good      Fair
color
D        0.206290  0.120172  0.089041  0.058537  0.059524  0.083333  0.019048
E        0.186864  0.167382  0.123288  0.146341  0.261905  0.239583  0.042857
F        0.185939  0.190987  0.287671  0.165854  0.154762  0.197917  0.166667
G        0.150786  0.171674  0.109589  0.224390  0.190476  0.197917  0.252381
H        0.146161  0.195279  0.260274  0.224390  0.142857  0.145833  0.247619
I        0.074931  0.096567  0.116438  0.117073  0.095238  0.093750  0.161905
J        0.049029  0.057940  0.013699  0.063415  0.095238  0.041667  0.109524

[7 rows x 40 columns]

# Removing multiindex

## a. Remove Multiindex for rows

#### 1. reset_index()

In [23]:
grouped_df.head()

             carat  depth  table  price     x      y     z
cut   color
Ideal D       2.75   64.5   62.0  18693  9.04   8.98  5.49
      E       2.28   65.5   62.0  18729  8.52  31.80  5.25
      F       2.45   65.3   63.0  18780  8.67   8.64  5.36
      G       2.54   64.1   62.0  18806  8.75   8.69  5.46
      H       3.50   65.1   62.0  18760  9.65   9.59  6.03

In [24]:
#resets both and creates a range index
grouped_df.reset_index()

          cut color  carat  depth  table  price      x      y      z
0       Ideal     D   2.75   64.5   62.0  18693   9.04   8.98   5.49
1       Ideal     E   2.28   65.5   62.0  18729   8.52  31.80   5.25
2       Ideal     F   2.45   65.3   63.0  18780   8.67   8.64   5.36
3       Ideal     G   2.54   64.1   62.0  18806   8.75   8.69   5.46
4       Ideal     H   3.50   65.1   62.0  18760   9.65   9.59   6.03
5       Ideal     I   3.22   66.7   62.0  18779   9.49   9.42   5.92
6       Ideal     J   3.01   65.4   62.0  18508   9.25   9.20   5.86
7     Premium     D   2.57   63.0   62.0  18575   8.99   8.94   5.28
8     Premium     E   3.05   63.0   62.0  18477   9.26   9.25   5.66
9     Premium     F   3.01   63.0   62.0  18791   9.24   9.13   5.73
10    Premium     G   3.01   63.0   62.0  18741   9.44   9.37   5.62
11    Premium     H   3.24   63.0   62.0  18795   9.44  58.90   8.06
12    Premium     I   4.01   63.0   62.0  18823  10.14  10.10   6.17
13    Premium     J   4.01   63.0   62.0  18710  10.02   9.94   6.24
14  Very Good     D   2.58   64.7   64.0  18542   9.08   9.01   5.33
15  Very Good     E   2.51   64.5   65.0  18731   8.65   8.60  31.80
16  Very Good     F   2.48   64.5   65.0  18777   8.64   8.55   5.45
17  Very Good     G   2.52   64.9   66.0  18818   8.65   8.61   5.45
18  Very Good     H   3.00   64.7   65.0  18803   9.23   9.10   5.77
19  Very Good     I   4.00   64.4   65.0  18500  10.01   9.94   6.31
20  Very Good     J   2.74   64.1   63.0  18430   8.89   8.93   5.47
21       Good     D   2.04   67.0   66.0  18468   8.15   8.11   5.11
22       Good     E   3.00   65.9   65.0  18236   9.08   8.96   5.79
23       Good     F   2.67   66.5   66.0  18686   8.69   8.64   5.54
24       Good     G   2.80   65.8   66.0  18788   8.90   8.85   5.44
25       Good     H   3.01   66.1   65.0  18640   9.44   9.38   5.58
26       Good     I   3.01   65.9   66.0  18707   9.38   9.31   5.77
27       Good     J   3.00   66.0   65.0  18325   9.32   9.19   5.50
28       Fair     D   3.40   71.6   73.0  16386   9.42   9.34   6.27
29       Fair     E   2.04   79.0   73.0  15584   8.16   8.04   5.24
30       Fair     F   2.58   71.0   95.0  17995   8.58   8.51   5.57
31       Fair     G   2.60   72.9   76.0  18574   8.75   8.69   6.16
32       Fair     H   4.13   71.8   73.0  18565  10.00   9.85   6.43
33       Fair     I   3.02   71.3   70.0  18242   9.11   9.02   5.91
34       Fair     J   5.01   73.6   68.0  18531  10.74  10.54   6.98

In [25]:
#Resets cut and maintains 'clarity' as the index
#grouped_df.reset_index(level=0)
grouped_df.reset_index(
    level = 'cut')

             cut  carat  depth  table  price      x      y      z
color
D          Ideal   2.75   64.5   62.0  18693   9.04   8.98   5.49
E          Ideal   2.28   65.5   62.0  18729   8.52  31.80   5.25
F          Ideal   2.45   65.3   63.0  18780   8.67   8.64   5.36
G          Ideal   2.54   64.1   62.0  18806   8.75   8.69   5.46
H          Ideal   3.50   65.1   62.0  18760   9.65   9.59   6.03
I          Ideal   3.22   66.7   62.0  18779   9.49   9.42   5.92
J          Ideal   3.01   65.4   62.0  18508   9.25   9.20   5.86
D        Premium   2.57   63.0   62.0  18575   8.99   8.94   5.28
E        Premium   3.05   63.0   62.0  18477   9.26   9.25   5.66
F        Premium   3.01   63.0   62.0  18791   9.24   9.13   5.73
G        Premium   3.01   63.0   62.0  18741   9.44   9.37   5.62
H        Premium   3.24   63.0   62.0  18795   9.44  58.90   8.06
I        Premium   4.01   63.0   62.0  18823  10.14  10.10   6.17
J        Premium   4.01   63.0   62.0  18710  10.02   9.94   6.24
D      Very Good   2.58   64.7   64.0  18542   9.08   9.01   5.33
E      Very Good   2.51   64.5   65.0  18731   8.65   8.60  31.80
F      Very Good   2.48   64.5   65.0  18777   8.64   8.55   5.45
G      Very Good   2.52   64.9   66.0  18818   8.65   8.61   5.45
H      Very Good   3.00   64.7   65.0  18803   9.23   9.10   5.77
I      Very Good   4.00   64.4   65.0  18500  10.01   9.94   6.31
J      Very Good   2.74   64.1   63.0  18430   8.89   8.93   5.47
D           Good   2.04   67.0   66.0  18468   8.15   8.11   5.11
E           Good   3.00   65.9   65.0  18236   9.08   8.96   5.79
F           Good   2.67   66.5   66.0  18686   8.69   8.64   5.54
G           Good   2.80   65.8   66.0  18788   8.90   8.85   5.44
H           Good   3.01   66.1   65.0  18640   9.44   9.38   5.58
I           Good   3.01   65.9   66.0  18707   9.38   9.31   5.77
J           Good   3.00   66.0   65.0  18325   9.32   9.19   5.50
D           Fair   3.40   71.6   73.0  16386   9.42   9.34   6.27
E           Fair   2.04   79.0   73.0  15584   8.16   8.04   5.24
F           Fair   2.58   71.0   95.0  17995   8.58   8.51   5.57
G           Fair   2.60   72.9   76.0  18574   8.75   8.69   6.16
H           Fair   4.13   71.8   73.0  18565  10.00   9.85   6.43
I           Fair   3.02   71.3   70.0  18242   9.11   9.02   5.91
J           Fair   5.01   73.6   68.0  18531  10.74  10.54   6.98

In [26]:
many_aggs_df = diamonds.groupby('cut').agg(['median','max','mean'])

many_aggs_df

           carat                  depth                   table        \
          median   max      mean median   max       mean median   max
cut
Ideal       0.54  3.50  0.702837   61.8  66.7  61.709401   56.0  63.0
Premium     0.86  4.01  0.891955   61.4  63.0  61.264673   59.0  62.0
Very Good   0.71  4.00  0.806381   62.1  64.9  61.818275   58.0  66.0
Good        0.82  3.01  0.849185   63.4  67.0  62.365879   58.0  66.0
Fair        1.00  5.01  1.046137   65.0  79.0  64.041677   58.0  95.0

                       price  ...                   x                       y  \
                mean  median  ...         mean median    max      mean median
cut                           ...
Ideal      55.951668  1810.0  ...  3457.541970  5.250   9.65  5.507451   5.26
Premium    58.746095  3185.0  ...  4584.257704  6.110  10.14  5.973887   6.06
Very Good  57.956150  2648.0  ...  3981.759891  5.740  10.01  5.740696   5.77
Good       58.694639  3050.5  ...  3928.864452  5.980   9.44  5.838785   5.99
Fair       59.053789  3282.0  ...  4358.757764  6.175  10.74  6.246894   6.10

                                z
             max      mean median    max      mean
cut
Ideal      31.80  5.520080   3.23   6.03  3.401448
Premium    58.90  5.944879   3.72   8.06  3.647124
Very Good   9.94  5.770026   3.56  31.80  3.559801
Good        9.38  5.850744   3.70   5.79  3.639507
Fair       10.54  6.182652   3.97   6.98  3.982770

[5 rows x 21 columns]

In [27]:
#reset the index but still maintain multiple column-header levels
many_aggs_df.reset_index()

         cut  carat                  depth                   table        \
             median   max      mean median   max       mean median   max
0      Ideal   0.54  3.50  0.702837   61.8  66.7  61.709401   56.0  63.0
1    Premium   0.86  4.01  0.891955   61.4  63.0  61.264673   59.0  62.0
2  Very Good   0.71  4.00  0.806381   62.1  64.9  61.818275   58.0  66.0
3       Good   0.82  3.01  0.849185   63.4  67.0  62.365879   58.0  66.0
4       Fair   1.00  5.01  1.046137   65.0  79.0  64.041677   58.0  95.0

              ...        price      x                       y         \
        mean  ...         mean median    max      mean median    max
0  55.951668  ...  3457.541970  5.250   9.65  5.507451   5.26  31.80
1  58.746095  ...  4584.257704  6.110  10.14  5.973887   6.06  58.90
2  57.956150  ...  3981.759891  5.740  10.01  5.740696   5.77   9.94
3  58.694639  ...  3928.864452  5.980   9.44  5.838785   5.99   9.38
4  59.053789  ...  4358.757764  6.175  10.74  6.246894   6.10  10.54

                 z
       mean median    max      mean
0  5.520080   3.23   6.03  3.401448
1  5.944879   3.72   8.06  3.647124
2  5.770026   3.56  31.80  3.559801
3  5.850744   3.70   5.79  3.639507
4  6.182652   3.97   6.98  3.982770

[5 rows x 22 columns]

### 2. df.droplevel(level_to_drop, axis=0)
Used If you want to completely remove an index.

An index level must be left after dropping, therefore to drop one level there must be 2, to drop 2 levels there must be 3 etc.

In [28]:
grouped_df

                 carat  depth  table  price      x      y      z
cut       color
Ideal     D       2.75   64.5   62.0  18693   9.04   8.98   5.49
          E       2.28   65.5   62.0  18729   8.52  31.80   5.25
          F       2.45   65.3   63.0  18780   8.67   8.64   5.36
          G       2.54   64.1   62.0  18806   8.75   8.69   5.46
          H       3.50   65.1   62.0  18760   9.65   9.59   6.03
          I       3.22   66.7   62.0  18779   9.49   9.42   5.92
          J       3.01   65.4   62.0  18508   9.25   9.20   5.86
Premium   D       2.57   63.0   62.0  18575   8.99   8.94   5.28
          E       3.05   63.0   62.0  18477   9.26   9.25   5.66
          F       3.01   63.0   62.0  18791   9.24   9.13   5.73
          G       3.01   63.0   62.0  18741   9.44   9.37   5.62
          H       3.24   63.0   62.0  18795   9.44  58.90   8.06
          I       4.01   63.0   62.0  18823  10.14  10.10   6.17
          J       4.01   63.0   62.0  18710  10.02   9.94   6.24
Very Good D       2.58   64.7   64.0  18542   9.08   9.01   5.33
          E       2.51   64.5   65.0  18731   8.65   8.60  31.80
          F       2.48   64.5   65.0  18777   8.64   8.55   5.45
          G       2.52   64.9   66.0  18818   8.65   8.61   5.45
          H       3.00   64.7   65.0  18803   9.23   9.10   5.77
          I       4.00   64.4   65.0  18500  10.01   9.94   6.31
          J       2.74   64.1   63.0  18430   8.89   8.93   5.47
Good      D       2.04   67.0   66.0  18468   8.15   8.11   5.11
          E       3.00   65.9   65.0  18236   9.08   8.96   5.79
          F       2.67   66.5   66.0  18686   8.69   8.64   5.54
          G       2.80   65.8   66.0  18788   8.90   8.85   5.44
          H       3.01   66.1   65.0  18640   9.44   9.38   5.58
          I       3.01   65.9   66.0  18707   9.38   9.31   5.77
          J       3.00   66.0   65.0  18325   9.32   9.19   5.50
Fair      D       3.40   71.6   73.0  16386   9.42   9.34   6.27
          E       2.04   79.0   73.0  15584   8.16   8.04   5.24
          F       2.58   71.0   95.0  17995   8.58   8.51   5.57
          G       2.60   72.9   76.0  18574   8.75   8.69   6.16
          H       4.13   71.8   73.0  18565  10.00   9.85   6.43
          I       3.02   71.3   70.0  18242   9.11   9.02   5.91
          J       5.01   73.6   68.0  18531  10.74  10.54   6.98

In [29]:
#drops the second level, 'color'
grouped_df.droplevel(level = 1, axis=0)

           carat  depth  table  price      x      y      z
cut
Ideal       2.75   64.5   62.0  18693   9.04   8.98   5.49
Ideal       2.28   65.5   62.0  18729   8.52  31.80   5.25
Ideal       2.45   65.3   63.0  18780   8.67   8.64   5.36
Ideal       2.54   64.1   62.0  18806   8.75   8.69   5.46
Ideal       3.50   65.1   62.0  18760   9.65   9.59   6.03
Ideal       3.22   66.7   62.0  18779   9.49   9.42   5.92
Ideal       3.01   65.4   62.0  18508   9.25   9.20   5.86
Premium     2.57   63.0   62.0  18575   8.99   8.94   5.28
Premium     3.05   63.0   62.0  18477   9.26   9.25   5.66
Premium     3.01   63.0   62.0  18791   9.24   9.13   5.73
Premium     3.01   63.0   62.0  18741   9.44   9.37   5.62
Premium     3.24   63.0   62.0  18795   9.44  58.90   8.06
Premium     4.01   63.0   62.0  18823  10.14  10.10   6.17
Premium     4.01   63.0   62.0  18710  10.02   9.94   6.24
Very Good   2.58   64.7   64.0  18542   9.08   9.01   5.33
Very Good   2.51   64.5   65.0  18731   8.65   8.60  31.80
Very Good   2.48   64.5   65.0  18777   8.64   8.55   5.45
Very Good   2.52   64.9   66.0  18818   8.65   8.61   5.45
Very Good   3.00   64.7   65.0  18803   9.23   9.10   5.77
Very Good   4.00   64.4   65.0  18500  10.01   9.94   6.31
Very Good   2.74   64.1   63.0  18430   8.89   8.93   5.47
Good        2.04   67.0   66.0  18468   8.15   8.11   5.11
Good        3.00   65.9   65.0  18236   9.08   8.96   5.79
Good        2.67   66.5   66.0  18686   8.69   8.64   5.54
Good        2.80   65.8   66.0  18788   8.90   8.85   5.44
Good        3.01   66.1   65.0  18640   9.44   9.38   5.58
Good        3.01   65.9   66.0  18707   9.38   9.31   5.77
Good        3.00   66.0   65.0  18325   9.32   9.19   5.50
Fair        3.40   71.6   73.0  16386   9.42   9.34   6.27
Fair        2.04   79.0   73.0  15584   8.16   8.04   5.24
Fair        2.58   71.0   95.0  17995   8.58   8.51   5.57
Fair        2.60   72.9   76.0  18574   8.75   8.69   6.16
Fair        4.13   71.8   73.0  18565  10.00   9.85   6.43
Fair        3.02   71.3   70.0  18242   9.11   9.02   5.91
Fair        5.01   73.6   68.0  18531  10.74  10.54   6.98

### 3) df.index.droplevel('cut)

In [30]:
grouped_df = diamonds.groupby(['cut','color']).max()
grouped_df.head()

             carat  depth  table  price     x      y     z
cut   color
Ideal D       2.75   64.5   62.0  18693  9.04   8.98  5.49
      E       2.28   65.5   62.0  18729  8.52  31.80  5.25
      F       2.45   65.3   63.0  18780  8.67   8.64  5.36
      G       2.54   64.1   62.0  18806  8.75   8.69  5.46
      H       3.50   65.1   62.0  18760  9.65   9.59  6.03

In [31]:
#Assign the new index list to the df's index
grouped_df.index = grouped_df.index.droplevel('color')

In [32]:
grouped_df.head()

       carat  depth  table  price     x      y     z
cut
Ideal   2.75   64.5   62.0  18693  9.04   8.98  5.49
Ideal   2.28   65.5   62.0  18729  8.52  31.80  5.25
Ideal   2.45   65.3   63.0  18780  8.67   8.64  5.36
Ideal   2.54   64.1   62.0  18806  8.75   8.69  5.46
Ideal   3.50   65.1   62.0  18760  9.65   9.59  6.03

## b) Removing multiple column header levels

### 1. Merge the column levels into 1

In [33]:
many_aggs_df = diamonds.groupby(
    'cut').agg(
    ['median','max','mean'])

many_aggs_df

           carat                  depth                   table        \
          median   max      mean median   max       mean median   max
cut
Ideal       0.54  3.50  0.702837   61.8  66.7  61.709401   56.0  63.0
Premium     0.86  4.01  0.891955   61.4  63.0  61.264673   59.0  62.0
Very Good   0.71  4.00  0.806381   62.1  64.9  61.818275   58.0  66.0
Good        0.82  3.01  0.849185   63.4  67.0  62.365879   58.0  66.0
Fair        1.00  5.01  1.046137   65.0  79.0  64.041677   58.0  95.0

                       price  ...                   x                       y  \
                mean  median  ...         mean median    max      mean median
cut                           ...
Ideal      55.951668  1810.0  ...  3457.541970  5.250   9.65  5.507451   5.26
Premium    58.746095  3185.0  ...  4584.257704  6.110  10.14  5.973887   6.06
Very Good  57.956150  2648.0  ...  3981.759891  5.740  10.01  5.740696   5.77
Good       58.694639  3050.5  ...  3928.864452  5.980   9.44  5.838785   5.99
Fair       59.053789  3282.0  ...  4358.757764  6.175  10.74  6.246894   6.10

                                z
             max      mean median    max      mean
cut
Ideal      31.80  5.520080   3.23   6.03  3.401448
Premium    58.90  5.944879   3.72   8.06  3.647124
Very Good   9.94  5.770026   3.56  31.80  3.559801
Good        9.38  5.850744   3.70   5.79  3.639507
Fair       10.54  6.182652   3.97   6.98  3.982770

[5 rows x 21 columns]

In [34]:
df = many_aggs_df.copy()

In [35]:
df.columns

MultiIndex([('carat', 'median'),
            ('carat',    'max'),
            ('carat',   'mean'),
            ('depth', 'median'),
            ('depth',    'max'),
            ('depth',   'mean'),
            ('table', 'median'),
            ('table',    'max'),
            ('table',   'mean'),
            ('price', 'median'),
            ('price',    'max'),
            ('price',   'mean'),
            (    'x', 'median'),
            (    'x',    'max'),
            (    'x',   'mean'),
            (    'y', 'median'),
            (    'y',    'max'),
            (    'y',   'mean'),
            (    'z', 'median'),
            (    'z',    'max'),
            (    'z',   'mean')],
           )

In [36]:
df = many_aggs_df.copy()
df.columns = df.columns.map('_'.join)
df

,carat_median,carat_max,carat_mean,depth_median,depth_max,depth_mean,table_median,table_max,table_mean,price_median,...,price_mean,x_median,x_max,x_mean,y_median,y_max,y_mean,z_median,z_max,z_mean
cut,,,,,,,,,,,,,,,,,,,,,
Ideal,0.54,3.50,0.702837,61.8,66.7,61.709401,56.0,63.0,55.951668,1810.0,...,3457.541970,5.250,9.65,5.507451,5.26,31.80,5.520080,3.23,6.03,3.401448
Premium,0.86,4.01,0.891955,61.4,63.0,61.264673,59.0,62.0,58.746095,3185.0,...,4584.257704,6.110,10.14,5.973887,6.06,58.90,5.944879,3.72,8.06,3.647124
Very Good,0.71,4.00,0.806381,62.1,64.9,61.818275,58.0,66.0,57.956150,2648.0,...,3981.759891,5.740,10.01,5.740696,5.77,9.94,5.770026,3.56,31.80,3.559801
Good,0.82,3.01,0.849185,63.4,67.0,62.365879,58.0,66.0,58.694639,3050.5,...,3928.864452,5.980,9.44,5.838785,5.99,9.38,5.850744,3.70,5.79,3.639507
Fair,1.00,5.01,1.046137,65.0,79.0,64.041677,58.0,95.0,59.053789,3282.0,...,4358.757764,6.175,10.74,6.246894,6.10,10.54,6.182652,3.97,6.98,3.982770

In [37]:
df = many_aggs_df.copy()
df.columns = [f'{j}#{i}' for i,j in df.columns]
df

,median#carat,max#carat,mean#carat,median#depth,max#depth,mean#depth,median#table,max#table,mean#table,median#price,...,mean#price,median#x,max#x,mean#x,median#y,max#y,mean#y,median#z,max#z,mean#z
cut,,,,,,,,,,,,,,,,,,,,,
Ideal,0.54,3.50,0.702837,61.8,66.7,61.709401,56.0,63.0,55.951668,1810.0,...,3457.541970,5.250,9.65,5.507451,5.26,31.80,5.520080,3.23,6.03,3.401448
Premium,0.86,4.01,0.891955,61.4,63.0,61.264673,59.0,62.0,58.746095,3185.0,...,4584.257704,6.110,10.14,5.973887,6.06,58.90,5.944879,3.72,8.06,3.647124
Very Good,0.71,4.00,0.806381,62.1,64.9,61.818275,58.0,66.0,57.956150,2648.0,...,3981.759891,5.740,10.01,5.740696,5.77,9.94,5.770026,3.56,31.80,3.559801
Good,0.82,3.01,0.849185,63.4,67.0,62.365879,58.0,66.0,58.694639,3050.5,...,3928.864452,5.980,9.44,5.838785,5.99,9.38,5.850744,3.70,5.79,3.639507
Fair,1.00,5.01,1.046137,65.0,79.0,64.041677,58.0,95.0,59.053789,3282.0,...,4358.757764,6.175,10.74,6.246894,6.10,10.54,6.182652,3.97,6.98,3.982770

In [38]:
df = many_aggs_df.copy()
df.columns = ['|'.join(s) for s in df.columns]
df

,carat|median,carat|max,carat|mean,depth|median,depth|max,depth|mean,table|median,table|max,table|mean,price|median,...,price|mean,x|median,x|max,x|mean,y|median,y|max,y|mean,z|median,z|max,z|mean
cut,,,,,,,,,,,,,,,,,,,,,
Ideal,0.54,3.50,0.702837,61.8,66.7,61.709401,56.0,63.0,55.951668,1810.0,...,3457.541970,5.250,9.65,5.507451,5.26,31.80,5.520080,3.23,6.03,3.401448
Premium,0.86,4.01,0.891955,61.4,63.0,61.264673,59.0,62.0,58.746095,3185.0,...,4584.257704,6.110,10.14,5.973887,6.06,58.90,5.944879,3.72,8.06,3.647124
Very Good,0.71,4.00,0.806381,62.1,64.9,61.818275,58.0,66.0,57.956150,2648.0,...,3981.759891,5.740,10.01,5.740696,5.77,9.94,5.770026,3.56,31.80,3.559801
Good,0.82,3.01,0.849185,63.4,67.0,62.365879,58.0,66.0,58.694639,3050.5,...,3928.864452,5.980,9.44,5.838785,5.99,9.38,5.850744,3.70,5.79,3.639507
Fair,1.00,5.01,1.046137,65.0,79.0,64.041677,58.0,95.0,59.053789,3282.0,...,4358.757764,6.175,10.74,6.246894,6.10,10.54,6.182652,3.97,6.98,3.982770

### 2. df.droplevel(level, axis = 1)
There must be atleast 2 levels

In [42]:
df = diamonds.groupby('cut').agg(['max', 'median', 'min','mean'])
df

          carat                        depth                         table  \
            max median   min      mean   max median   min       mean   max
cut
Ideal      3.50   0.54  0.20  0.702837  66.7   61.8  43.0  61.709401  63.0
Premium    4.01   0.86  0.20  0.891955  63.0   61.4  58.0  61.264673  62.0
Very Good  4.00   0.71  0.20  0.806381  64.9   62.1  56.8  61.818275  66.0
Good       3.01   0.82  0.23  0.849185  67.0   63.4  54.3  62.365879  66.0
Fair       5.01   1.00  0.22  1.046137  79.0   65.0  43.0  64.041677  95.0

                  ...    x                y                            z  \
          median  ...  min      mean    max median  min      mean    max
cut               ...
Ideal       56.0  ...  0.0  5.507451  31.80   5.26  0.0  5.520080   6.03
Premium     59.0  ...  0.0  5.973887  58.90   6.06  0.0  5.944879   8.06
Very Good   58.0  ...  0.0  5.740696   9.94   5.77  0.0  5.770026  31.80
Good        58.0  ...  0.0  5.838785   9.38   5.99  0.0  5.850744   5.79
Fair        58.0  ...  0.0  6.246894  10.54   6.10  0.0  6.182652   6.98


          median  min      mean
cut
Ideal       3.23  0.0  3.401448
Premium     3.72  0.0  3.647124
Very Good   3.56  0.0  3.559801
Good        3.70  0.0  3.639507
Fair        3.97  0.0  3.982770

[5 rows x 28 columns]

In [44]:
df_price = df.xs(key='price', axis=1, level=0, drop_level=False)
df_price

           price
             max  median  min         mean
cut
Ideal      18806  1810.0  326  3457.541970
Premium    18823  3185.0  326  4584.257704
Very Good  18818  2648.0  336  3981.759891
Good       18788  3050.5  327  3928.864452
Fair       18574  3282.0  337  4358.757764

In [63]:
df_price.droplevel(level=0, axis=1)

             max  median  min         mean
cut
Ideal      18806  1810.0  326  3457.541970
Premium    18823  3185.0  326  4584.257704
Very Good  18818  2648.0  336  3981.759891
Good       18788  3050.5  327  3928.864452
Fair       18574  3282.0  337  4358.757764

### 3. df.columns.droplevel(level_to_drop)

In [45]:
df = df_price.copy()

df.columns = df.columns.droplevel(0)
display(df)

             max  median  min         mean
cut
Ideal      18806  1810.0  326  3457.541970
Premium    18823  3185.0  326  4584.257704
Very Good  18818  2648.0  336  3981.759891
Good       18788  3050.5  327  3928.864452
Fair       18574  3282.0  337  4358.757764

### 4. df.columns.get_level_values(level_to_return)

In [47]:
df = df_price.copy()
df.columns = df.columns.get_level_values(1)
display(df)

             max  median  min         mean
cut
Ideal      18806  1810.0  326  3457.541970
Premium    18823  3185.0  326  4584.257704
Very Good  18818  2648.0  336  3981.759891
Good       18788  3050.5  327  3928.864452
Fair       18574  3282.0  337  4358.757764